### ISSUE TITLE
Beta Release

### ISSUE THREAD

**Issue by w1ndy** [w1ndy/vue-webpack-ts-template#1]
* [x] ``TypeError: cb is not a function`` in Server.ts (fixed via fc36f6773bb5831277bf4ce0de6aab05a580a2b2)
* [x] Message undefined in notifications (fixed via e0986790d8deb28b1b9690659c330d9e0b021bb6)
* [x] TSLint is not enabled (fixed via 50c88214cea4edbf93c186709f4dee604b333c88 and f9e0478d459a5ca7a30943711fb1aef0b9b597bf)
* [x] Lint files on the fly (fixed via 6c714464b278282a810f1f0cb1aa29bc0df583ab and ae6adc81facdb92fcd574316974a58b00691bd90)
* [ ] Support seamless template upgrade

**Comment by zikunrain** [comment]
Every time I clone this template and run dev, it throws an ERROR about devServer: line56 of /config/webpack/BaseWebpackConfiguration.ts
`  devServer: {
    historyApiFallback: true
  },`

Only when I delete it, project works.
Besides, it also throws Tslint warning of "consecutive-blank-lines" when I first run dev.

**Comment by w1ndy** [comment]
@zikunrain Your issue has been moved to #4 .

**Comment by w1ndy** [comment]
Closing in favor of the Beta milestone.
